### ISSUE TITLE
CPPDEF flag misspelled: DMI_CICE_COUPLEd -> DMI_CICE_COUPLED

### ISSUE THREAD

**Issue by mhrib** [HYCOM/HYCOM-src#10]
CPPDEF-flag misspelled in mod_hycom.F90 : linie 3640
#if defined (DMI_CICE_COUPLEd)

Should be (capital D at the end):
#if defined (DMI_CICE_COUPLED)

**Comment by abozec** [comment]
corrected ! thanks

On May 15, 2020, at 7:33 PM, Mads Hvid Ribergaard <notifications@github.com<mailto:notifications@github.com>> wrote:



CPPDEF-flag misspelled in mod_hycom.F90 : linie 3640
#if defined (DMI_CICE_COUPLEd)

Should be (capital D at the end):
#if defined (DMI_CICE_COUPLED)
