### ISSUE TITLE
Update non-standard call flush() to the standard flush() statement

### ISSUE THREAD

**Issue by milancurcic** [HYCOM/HYCOM-src#11]
I'm porting v2.3.01 to IBM Power9 with XL v16.1.1, and it complains at link time that a `flush` subroutine is not available. Indeed this is a non-standard extension. Fortran now includes a `flush` statement which works the same way.

To make HYCOM build with XL v16.1.1, this is sufficient:

```
sed -i "s/call flush/flush/gi" *{h,F90}
```

Would you like a PR?

**Comment by awallcraft** [comment]
Milan,

We have not used a Power system for a long time, but the macros AIX and
AIX_NOFL are still in the source code:

gaffney01 125> grep "AIX" *90 *h *.c
machine.F90:#if defined(AIX)
machine.F90:! --- wrapper for flush system call under AIX.
machine.F90:#endif /* AIX */
wtime.F90:#if defined(AIX)
mod_xc_mp.h:#if defined(MPI) && defined(AIX) && ! (defined(AIX_NOFL) ||
defined(USE_ESMF4)  || defined(ESPC_COUPLE) || defined(OCEANS2))
mod_za_mp.h:#if defined(AIX)
machi_c.c:#if defined(AIX)
machi_c.c:#endif /* AIX */

machine.F90 contains machine-specific wrappers for the flush subroutine,
and uses call flush_ under AIX, but also has an example if using the flush
statement in a wrapper.

Please see if -DAIX or -DAIX -DAIX_NOFL still makes sense for the Power9.
It is probably OK to modify the existing macro fragments, or you could add
an AIX9 (say) macro to use instead.

Alan.

**Comment by milancurcic** [comment]
Thanks, Alan. This is Linux on IBM, not AIX, but the `flush_` may very well be available. I will try it and let you know.

**Comment by awallcraft** [comment]
The AIX macro is really for XLF and IBM POE and IBM MPI, but some of the
optimizations may be out of date or not applicable to IBM's Linux
versions.  If you introduce a new macro, then you may as well use flush
rather than call flush_ in machine.F90.

**Comment by milancurcic** [comment]
Using `-DAIX` triggers:

```
machi_c.c:26:10: fatal error: 'sys/systemcfg.h' file not found
#include <sys/systemcfg.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
Error while processing machi_c.c.
```

In machine.F90 I introduced:

```
#if defined(POWER9)
      subroutine flush(iunit)
      implicit none
      integer iunit
!
! --- wrapper for flush system call under Power9.
!
      integer*4 iunit4
!
      iunit4=iunit
      flush(iunit4)
      end
#endif /* POWER9 */
```

and this builds and runs. I also have this config file:

```
#
# ------------------------------------------------------------------------------
# common definitions for XL Fortran and Spectrum MPI on IBM Power9 Linux.
# version that uses Serial I/O for HYCOM
# relocatable version
# ------------------------------------------------------------------------------
#
# MACROS      DESCRIPTIONS:
#
# FC:         Fortran 90 compiler.
# FCFFLAGS:   Fortran 90 compilation flags.
# CC:         C compiler.
# CCFLAGS:    C compilation flags.
# CPP:        cpp preprocessor (may be implied by FC).
# CPPFLAGS:   cpp -D macro flags.
# LD:         Loader.
# LDFLAGS:    Loader flags.
# EXTRALIBS:  Extra local libraries (if any).
#
FC            = mpif90
FCFFLAGS      = -O3 -qstrict -qrealsize=8 -qufmt=be
CC            = xlc
CCFLAGS       = -O
CPP           = cpp -P
CPPFLAGS      = -DREAL8 -DMPI -DSERIAL_IO -DTIMER -DRELO -DPOWER9 $(CPP_EXTRAS)
LD            = $(FC)
LDFLAGS       = -v $(FCFFLAGS)
EXTRALIBS     =

#
# --- generic make definitions
#
SHELL         = /bin/sh
RM            = \rm -f

#
# rules.
#

.c.o:
        $(CC) $(CPPFLAGS) $(CCFLAGS)  -c $*.c

.F90.o:
        $(FC) $(CPPFLAGS) $(FCFFLAGS) -c $*.F90
```

Here I put `-O3 -qstrict` as the "safe" optimization (high optimization without change in semantics), but from my short experiments I found that `-O5` (changes semantics + heavy IPO) runs seemingly okay as well.

Would you like a PR with the POWER9 macro definition of `flush` and the config? I thought POWER9 is more appropriate than AIX9 as this is not really AIX.

**Comment by awallcraft** [comment]
Yes, please submit a PR.
